    <header id="inicio">
        <div class="topo">
            <h1 class="logo"><a href="">Compcom</a></h1>
            <ul class="social">
                <li><a href="" title=""><i class="fa fa-google fa-lg"></i></a></li>
                <li><a href="" title=""><i class="fa fa-twitter fa-lg"></i></a></li>
                <li><a href="" title=""><i class="fa fa-facebook fa-lg"></i></a></li>
            </ul>
        </div>
        <nav class="menu" id="alvo">
            <ul>
                <li><a href="#inicio" class="scroll">Inicio</a></li>
                <li><a href="#" class="scroll">Quem Somos</a></li>
                <li><a href="#servicos" class="scroll">Serviços</a></li>
                <li><a href="#" class="scroll">Portifolio</a></li>
                <li><a href="#orcamento" class="scroll">Orçamento</a></li>
                <li><a href="#local" class="scroll">Encontre-nos</a></li>
            </ul>
        </nav>
        <div id="owl-demo" class="owl-carousel owl-theme">
            <div class="item"><img src= "./Public/css/img/slide1.jpg" title="Plano manutenção de computadores empresarial" alt="Plano manutenção de computadores empresarial"></div>
            <div class="item"><img src="./Public/css/img/slide2.jpg" title="Manutenção de computadores residenciais" alt="Manutenção de computadores residenciais"></div>
            <div class="item"><img src="./Public/css/img/slide3.jpg" title="Criação de sites" alt="Criação de sites"></div>
            <div class="item"><img src="./Public/css/img/slide4.png" title="Gerenciamento de Midias Sociais" alt="Gerenciamento de Midias Sociais"></div>
            <div class="item"><img src="./Public/css/img/slide5.png" title="Criação de sites" alt="Criação de sites"></div>
        </div>
    </header>
    <article id="servicos" class="conteudo">
        <header>
            <h1><i class="fa fa-briefcase" aria-hidden="true"></i>Nossos Serviços</h1>
        </header>
        <article>
            <img src="./Public/css/img/plano-empresa.jpg" alt="">
            <h2>Manutenção de Computadores</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus nisi molestiae.</p>
        </article>
        <article>
            <img src="./Public/css/img/plano-casa.jpg" alt="">
            <h2>Criação de Sites</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus nisi molestiae.</p>
        </article>
        <article>
            <img src="./Public/css/img/plano-empresa.jpg" alt="">
            <h2>Administração de Redes Sociais</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus nisi molestiae.</p>
        </article>
        <article>
            <img src="./Public/css/img/plano-casa.jpg" alt="">
            <h2>Backup Profissional de Arquivos</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus nisi molestiae.</p>
        </article>
    </article>
    <section id="orcamento" class="orcamento">
        <div class="container">
            <h1><i class="fa fa-envelope" aria-hidden="true"></i>Orçamento</h1>
            <p>Caso queira um orçamento sobre algum serviço basta colocar <b>Assunto</b> como <b>Orçamento</b>.</p>
            <form action="/compcom/ValidaForm" method="post">
                <label for="nome">Nome: </label>
                <input type="text" name="nome" id="nome" placeholder="Nome" required>
                <label for="email">E-mail: </label>
                <input type="email" name="email" id="email" placeholder="seuemail@site.com" required>
                <label for="assunto">Assunto: </label>
                <input type="text" name="assunto" id="assunto" placeholder="Assunto" required>
                <label for="mensagem">Mensagem:</label>
                <textarea name="mensagem" id="mensagem" placeholder="Escreva aqui sua mensagem..." required></textarea>
                <input type="submit" value="Enviar">
            </form>
        </div>
    </section>
    <aside id="local" class="local">
        <h1><i class="fa fa-home" aria-hidden="true"></i>Onde Estamos</h1>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3719.6620579074347!2d-47.84264514987143!3d-21.205579684641485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94b9bea71e8df2d3%3A0x78063bf257909df4!2sR.+Imigrantes+Japoneses%2C+1074+-+Parque+Ribeirao+Preto%2C+Ribeir%C3%A3o+Preto+-+SP%2C+14031-160!5e0!3m2!1spt-BR!2sbr!4v1462340175891"></iframe>
        </div>
        <div class="dadoslocal">
            <p>Venha nos conhecer, estamos a inteira disposição</p>
            <br>
            <h3>Horario de Atendimento:</h3>
            <p>De segunda a sexta feira,</p>
            <p>das 08:00 as 18:00</p>
        </div>
    </aside>
    <footer>
        <div class="contato">
            <h1><i class="fa fa-comments-o" aria-hidden="true"></i>Fale Conosco</h1>

        </div>
        <div>
            <p>Desenvolvido por <b><i class="fa fa-copyright" aria-hidden="true"></i>Compcom</b></p>
        </div>
    </footer>